name: Continuous Integration

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: docker
    name: Continuous Integration
    steps:
      - uses: actions/checkout@v4

      - name: cargo test
        uses: docker://rust:latest
        with:
          args: cargo test
      # uncomment to enable clippy linter
      # - name: cargo clippy
      #   run: cargo clippy -- -D warnings
      # uncomment to enable format linter
      # - name: cargo fmt
      #   run: cargo fmt --check
